//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.02 at 03:58:23 PM EEST 
//


package org.model.xjc;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExpensesClassificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExpensesClassificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="classificationType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{https://www.aade.gr/myDATA/expensesClassificaton/v1.0}ExpensesClassificationValueType">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="classificationCategory" type="{https://www.aade.gr/myDATA/expensesClassificaton/v1.0}ExpensesClassificationCategoryType" minOccurs="0"/>
 *         &lt;element name="amount" type="{https://www.aade.gr/myDATA/expensesClassificaton/v1.0}AmountType"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExpensesClassificationType", namespace = "https://www.aade.gr/myDATA/expensesClassificaton/v1.0", propOrder = {
    "classificationType",
    "classificationCategory",
    "amount",
    "id"
})
public class ExpensesClassificationType {

    protected ExpensesClassificationValueType classificationType;
    @XmlSchemaType(name = "string")
    protected ExpensesClassificationCategoryType classificationCategory;
    @XmlElement(required = true)
    protected BigDecimal amount;
    protected Byte id;

    /**
     * Gets the value of the classificationType property.
     * 
     * @return
     *     possible object is
     *     {@link ExpensesClassificationValueType }
     *     
     */
    public ExpensesClassificationValueType getClassificationType() {
        return classificationType;
    }

    /**
     * Sets the value of the classificationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpensesClassificationValueType }
     *     
     */
    public void setClassificationType(ExpensesClassificationValueType value) {
        this.classificationType = value;
    }

    /**
     * Gets the value of the classificationCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ExpensesClassificationCategoryType }
     *     
     */
    public ExpensesClassificationCategoryType getClassificationCategory() {
        return classificationCategory;
    }

    /**
     * Sets the value of the classificationCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpensesClassificationCategoryType }
     *     
     */
    public void setClassificationCategory(ExpensesClassificationCategoryType value) {
        this.classificationCategory = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setId(Byte value) {
        this.id = value;
    }

}
