//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.02 at 03:58:23 PM EEST 
//


package org.model.xjc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExpensesClassificationValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExpensesClassificationValueType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="E3_101"/>
 *     &lt;enumeration value="E3_102_001"/>
 *     &lt;enumeration value="E3_102_002"/>
 *     &lt;enumeration value="E3_102_003"/>
 *     &lt;enumeration value="E3_102_004"/>
 *     &lt;enumeration value="E3_102_005"/>
 *     &lt;enumeration value="E3_102_006"/>
 *     &lt;enumeration value="E3_104"/>
 *     &lt;enumeration value="E3_201"/>
 *     &lt;enumeration value="E3_202_001"/>
 *     &lt;enumeration value="E3_202_002"/>
 *     &lt;enumeration value="E3_202_003"/>
 *     &lt;enumeration value="E3_202_004"/>
 *     &lt;enumeration value="E3_202_005"/>
 *     &lt;enumeration value="E3_204"/>
 *     &lt;enumeration value="E3_207"/>
 *     &lt;enumeration value="E3_209"/>
 *     &lt;enumeration value="E3_301"/>
 *     &lt;enumeration value="E3_302_001"/>
 *     &lt;enumeration value="E3_302_002"/>
 *     &lt;enumeration value="E3_302_003"/>
 *     &lt;enumeration value="E3_302_004"/>
 *     &lt;enumeration value="E3_302_005"/>
 *     &lt;enumeration value="E3_304"/>
 *     &lt;enumeration value="E3_307"/>
 *     &lt;enumeration value="E3_309"/>
 *     &lt;enumeration value="E3_312"/>
 *     &lt;enumeration value="E3_313_001"/>
 *     &lt;enumeration value="E3_313_002"/>
 *     &lt;enumeration value="E3_313_003"/>
 *     &lt;enumeration value="E3_313_004"/>
 *     &lt;enumeration value="E3_313_005"/>
 *     &lt;enumeration value="E3_315"/>
 *     &lt;enumeration value="E3_581_001"/>
 *     &lt;enumeration value="E3_581_002"/>
 *     &lt;enumeration value="E3_581_003"/>
 *     &lt;enumeration value="E3_582"/>
 *     &lt;enumeration value="E3_583"/>
 *     &lt;enumeration value="E3_584"/>
 *     &lt;enumeration value="E3_585_001"/>
 *     &lt;enumeration value="E3_585_002"/>
 *     &lt;enumeration value="E3_585_003"/>
 *     &lt;enumeration value="E3_585_004"/>
 *     &lt;enumeration value="E3_585_005"/>
 *     &lt;enumeration value="E3_585_006"/>
 *     &lt;enumeration value="E3_585_007"/>
 *     &lt;enumeration value="E3_585_008"/>
 *     &lt;enumeration value="E3_585_009"/>
 *     &lt;enumeration value="E3_585_010"/>
 *     &lt;enumeration value="E3_585_011"/>
 *     &lt;enumeration value="E3_585_012"/>
 *     &lt;enumeration value="E3_585_013"/>
 *     &lt;enumeration value="E3_585_014"/>
 *     &lt;enumeration value="E3_585_015"/>
 *     &lt;enumeration value="E3_585_016"/>
 *     &lt;enumeration value="E3_586"/>
 *     &lt;enumeration value="E3_587"/>
 *     &lt;enumeration value="E3_588"/>
 *     &lt;enumeration value="E3_589"/>
 *     &lt;enumeration value="E3_881_001"/>
 *     &lt;enumeration value="E3_881_002"/>
 *     &lt;enumeration value="E3_881_003"/>
 *     &lt;enumeration value="E3_881_004"/>
 *     &lt;enumeration value="E3_882_001"/>
 *     &lt;enumeration value="E3_882_002"/>
 *     &lt;enumeration value="E3_882_003"/>
 *     &lt;enumeration value="E3_882_004"/>
 *     &lt;enumeration value="E3_883_001"/>
 *     &lt;enumeration value="E3_883_002"/>
 *     &lt;enumeration value="E3_883_003"/>
 *     &lt;enumeration value="E3_883_004"/>
 *     &lt;enumeration value="VAT_361"/>
 *     &lt;enumeration value="VAT_362"/>
 *     &lt;enumeration value="VAT_363"/>
 *     &lt;enumeration value="VAT_364"/>
 *     &lt;enumeration value="VAT_365"/>
 *     &lt;enumeration value="VAT_366"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExpensesClassificationValueType", namespace = "https://www.aade.gr/myDATA/expensesClassificaton/v1.0")
@XmlEnum
public enum ExpensesClassificationValueType {

    @XmlEnumValue("E3_101")
    E_3_101("E3_101"),
    @XmlEnumValue("E3_102_001")
    E_3_102_001("E3_102_001"),
    @XmlEnumValue("E3_102_002")
    E_3_102_002("E3_102_002"),
    @XmlEnumValue("E3_102_003")
    E_3_102_003("E3_102_003"),
    @XmlEnumValue("E3_102_004")
    E_3_102_004("E3_102_004"),
    @XmlEnumValue("E3_102_005")
    E_3_102_005("E3_102_005"),
    @XmlEnumValue("E3_102_006")
    E_3_102_006("E3_102_006"),
    @XmlEnumValue("E3_104")
    E_3_104("E3_104"),
    @XmlEnumValue("E3_201")
    E_3_201("E3_201"),
    @XmlEnumValue("E3_202_001")
    E_3_202_001("E3_202_001"),
    @XmlEnumValue("E3_202_002")
    E_3_202_002("E3_202_002"),
    @XmlEnumValue("E3_202_003")
    E_3_202_003("E3_202_003"),
    @XmlEnumValue("E3_202_004")
    E_3_202_004("E3_202_004"),
    @XmlEnumValue("E3_202_005")
    E_3_202_005("E3_202_005"),
    @XmlEnumValue("E3_204")
    E_3_204("E3_204"),
    @XmlEnumValue("E3_207")
    E_3_207("E3_207"),
    @XmlEnumValue("E3_209")
    E_3_209("E3_209"),
    @XmlEnumValue("E3_301")
    E_3_301("E3_301"),
    @XmlEnumValue("E3_302_001")
    E_3_302_001("E3_302_001"),
    @XmlEnumValue("E3_302_002")
    E_3_302_002("E3_302_002"),
    @XmlEnumValue("E3_302_003")
    E_3_302_003("E3_302_003"),
    @XmlEnumValue("E3_302_004")
    E_3_302_004("E3_302_004"),
    @XmlEnumValue("E3_302_005")
    E_3_302_005("E3_302_005"),
    @XmlEnumValue("E3_304")
    E_3_304("E3_304"),
    @XmlEnumValue("E3_307")
    E_3_307("E3_307"),
    @XmlEnumValue("E3_309")
    E_3_309("E3_309"),
    @XmlEnumValue("E3_312")
    E_3_312("E3_312"),
    @XmlEnumValue("E3_313_001")
    E_3_313_001("E3_313_001"),
    @XmlEnumValue("E3_313_002")
    E_3_313_002("E3_313_002"),
    @XmlEnumValue("E3_313_003")
    E_3_313_003("E3_313_003"),
    @XmlEnumValue("E3_313_004")
    E_3_313_004("E3_313_004"),
    @XmlEnumValue("E3_313_005")
    E_3_313_005("E3_313_005"),
    @XmlEnumValue("E3_315")
    E_3_315("E3_315"),
    @XmlEnumValue("E3_581_001")
    E_3_581_001("E3_581_001"),
    @XmlEnumValue("E3_581_002")
    E_3_581_002("E3_581_002"),
    @XmlEnumValue("E3_581_003")
    E_3_581_003("E3_581_003"),
    @XmlEnumValue("E3_582")
    E_3_582("E3_582"),
    @XmlEnumValue("E3_583")
    E_3_583("E3_583"),
    @XmlEnumValue("E3_584")
    E_3_584("E3_584"),
    @XmlEnumValue("E3_585_001")
    E_3_585_001("E3_585_001"),
    @XmlEnumValue("E3_585_002")
    E_3_585_002("E3_585_002"),
    @XmlEnumValue("E3_585_003")
    E_3_585_003("E3_585_003"),
    @XmlEnumValue("E3_585_004")
    E_3_585_004("E3_585_004"),
    @XmlEnumValue("E3_585_005")
    E_3_585_005("E3_585_005"),
    @XmlEnumValue("E3_585_006")
    E_3_585_006("E3_585_006"),
    @XmlEnumValue("E3_585_007")
    E_3_585_007("E3_585_007"),
    @XmlEnumValue("E3_585_008")
    E_3_585_008("E3_585_008"),
    @XmlEnumValue("E3_585_009")
    E_3_585_009("E3_585_009"),
    @XmlEnumValue("E3_585_010")
    E_3_585_010("E3_585_010"),
    @XmlEnumValue("E3_585_011")
    E_3_585_011("E3_585_011"),
    @XmlEnumValue("E3_585_012")
    E_3_585_012("E3_585_012"),
    @XmlEnumValue("E3_585_013")
    E_3_585_013("E3_585_013"),
    @XmlEnumValue("E3_585_014")
    E_3_585_014("E3_585_014"),
    @XmlEnumValue("E3_585_015")
    E_3_585_015("E3_585_015"),
    @XmlEnumValue("E3_585_016")
    E_3_585_016("E3_585_016"),
    @XmlEnumValue("E3_586")
    E_3_586("E3_586"),
    @XmlEnumValue("E3_587")
    E_3_587("E3_587"),
    @XmlEnumValue("E3_588")
    E_3_588("E3_588"),
    @XmlEnumValue("E3_589")
    E_3_589("E3_589"),
    @XmlEnumValue("E3_881_001")
    E_3_881_001("E3_881_001"),
    @XmlEnumValue("E3_881_002")
    E_3_881_002("E3_881_002"),
    @XmlEnumValue("E3_881_003")
    E_3_881_003("E3_881_003"),
    @XmlEnumValue("E3_881_004")
    E_3_881_004("E3_881_004"),
    @XmlEnumValue("E3_882_001")
    E_3_882_001("E3_882_001"),
    @XmlEnumValue("E3_882_002")
    E_3_882_002("E3_882_002"),
    @XmlEnumValue("E3_882_003")
    E_3_882_003("E3_882_003"),
    @XmlEnumValue("E3_882_004")
    E_3_882_004("E3_882_004"),
    @XmlEnumValue("E3_883_001")
    E_3_883_001("E3_883_001"),
    @XmlEnumValue("E3_883_002")
    E_3_883_002("E3_883_002"),
    @XmlEnumValue("E3_883_003")
    E_3_883_003("E3_883_003"),
    @XmlEnumValue("E3_883_004")
    E_3_883_004("E3_883_004"),
    VAT_361("VAT_361"),
    VAT_362("VAT_362"),
    VAT_363("VAT_363"),
    VAT_364("VAT_364"),
    VAT_365("VAT_365"),
    VAT_366("VAT_366");
    private final String value;

    ExpensesClassificationValueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExpensesClassificationValueType fromValue(String v) {
        for (ExpensesClassificationValueType c: ExpensesClassificationValueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
