//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.02 at 03:58:23 PM EEST 
//


package org.model.xjc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExpensesClassificationCategoryType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExpensesClassificationCategoryType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="category2_1"/>
 *     &lt;enumeration value="category2_2"/>
 *     &lt;enumeration value="category2_3"/>
 *     &lt;enumeration value="category2_4"/>
 *     &lt;enumeration value="category2_5"/>
 *     &lt;enumeration value="category2_6"/>
 *     &lt;enumeration value="category2_7"/>
 *     &lt;enumeration value="category2_8"/>
 *     &lt;enumeration value="category2_9"/>
 *     &lt;enumeration value="category2_10"/>
 *     &lt;enumeration value="category2_11"/>
 *     &lt;enumeration value="category2_12"/>
 *     &lt;enumeration value="category2_13"/>
 *     &lt;enumeration value="category2_14"/>
 *     &lt;enumeration value="category2_95"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExpensesClassificationCategoryType", namespace = "https://www.aade.gr/myDATA/expensesClassificaton/v1.0")
@XmlEnum
public enum ExpensesClassificationCategoryType {

    @XmlEnumValue("category2_1")
    CATEGORY_2_1("category2_1"),
    @XmlEnumValue("category2_2")
    CATEGORY_2_2("category2_2"),
    @XmlEnumValue("category2_3")
    CATEGORY_2_3("category2_3"),
    @XmlEnumValue("category2_4")
    CATEGORY_2_4("category2_4"),
    @XmlEnumValue("category2_5")
    CATEGORY_2_5("category2_5"),
    @XmlEnumValue("category2_6")
    CATEGORY_2_6("category2_6"),
    @XmlEnumValue("category2_7")
    CATEGORY_2_7("category2_7"),
    @XmlEnumValue("category2_8")
    CATEGORY_2_8("category2_8"),
    @XmlEnumValue("category2_9")
    CATEGORY_2_9("category2_9"),
    @XmlEnumValue("category2_10")
    CATEGORY_2_10("category2_10"),
    @XmlEnumValue("category2_11")
    CATEGORY_2_11("category2_11"),
    @XmlEnumValue("category2_12")
    CATEGORY_2_12("category2_12"),
    @XmlEnumValue("category2_13")
    CATEGORY_2_13("category2_13"),
    @XmlEnumValue("category2_14")
    CATEGORY_2_14("category2_14"),
    @XmlEnumValue("category2_95")
    CATEGORY_2_95("category2_95");
    private final String value;

    ExpensesClassificationCategoryType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExpensesClassificationCategoryType fromValue(String v) {
        for (ExpensesClassificationCategoryType c: ExpensesClassificationCategoryType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
