//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.02 at 03:58:23 PM EEST 
//


package org.model.xjc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IncomeClassificationValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IncomeClassificationValueType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="E3_106"/>
 *     &lt;enumeration value="E3_205"/>
 *     &lt;enumeration value="E3_210"/>
 *     &lt;enumeration value="E3_305"/>
 *     &lt;enumeration value="E3_310"/>
 *     &lt;enumeration value="E3_318"/>
 *     &lt;enumeration value="E3_561_001"/>
 *     &lt;enumeration value="E3_561_002"/>
 *     &lt;enumeration value="E3_561_003"/>
 *     &lt;enumeration value="E3_561_004"/>
 *     &lt;enumeration value="E3_561_005"/>
 *     &lt;enumeration value="E3_561_006"/>
 *     &lt;enumeration value="E3_561_007"/>
 *     &lt;enumeration value="E3_562"/>
 *     &lt;enumeration value="E3_563"/>
 *     &lt;enumeration value="E3_564"/>
 *     &lt;enumeration value="E3_565"/>
 *     &lt;enumeration value="E3_566"/>
 *     &lt;enumeration value="E3_567"/>
 *     &lt;enumeration value="E3_568"/>
 *     &lt;enumeration value="E3_570"/>
 *     &lt;enumeration value="E3_595"/>
 *     &lt;enumeration value="E3_596"/>
 *     &lt;enumeration value="E3_597"/>
 *     &lt;enumeration value="E3_880_001"/>
 *     &lt;enumeration value="E3_880_002"/>
 *     &lt;enumeration value="E3_880_003"/>
 *     &lt;enumeration value="E3_880_004"/>
 *     &lt;enumeration value="E3_881_001"/>
 *     &lt;enumeration value="E3_881_002"/>
 *     &lt;enumeration value="E3_881_003"/>
 *     &lt;enumeration value="E3_881_004"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IncomeClassificationValueType", namespace = "https://www.aade.gr/myDATA/incomeClassificaton/v1.0")
@XmlEnum
public enum IncomeClassificationValueType {

    @XmlEnumValue("E3_106")
    E_3_106("E3_106"),
    @XmlEnumValue("E3_205")
    E_3_205("E3_205"),
    @XmlEnumValue("E3_210")
    E_3_210("E3_210"),
    @XmlEnumValue("E3_305")
    E_3_305("E3_305"),
    @XmlEnumValue("E3_310")
    E_3_310("E3_310"),
    @XmlEnumValue("E3_318")
    E_3_318("E3_318"),
    @XmlEnumValue("E3_561_001")
    E_3_561_001("E3_561_001"),
    @XmlEnumValue("E3_561_002")
    E_3_561_002("E3_561_002"),
    @XmlEnumValue("E3_561_003")
    E_3_561_003("E3_561_003"),
    @XmlEnumValue("E3_561_004")
    E_3_561_004("E3_561_004"),
    @XmlEnumValue("E3_561_005")
    E_3_561_005("E3_561_005"),
    @XmlEnumValue("E3_561_006")
    E_3_561_006("E3_561_006"),
    @XmlEnumValue("E3_561_007")
    E_3_561_007("E3_561_007"),
    @XmlEnumValue("E3_562")
    E_3_562("E3_562"),
    @XmlEnumValue("E3_563")
    E_3_563("E3_563"),
    @XmlEnumValue("E3_564")
    E_3_564("E3_564"),
    @XmlEnumValue("E3_565")
    E_3_565("E3_565"),
    @XmlEnumValue("E3_566")
    E_3_566("E3_566"),
    @XmlEnumValue("E3_567")
    E_3_567("E3_567"),
    @XmlEnumValue("E3_568")
    E_3_568("E3_568"),
    @XmlEnumValue("E3_570")
    E_3_570("E3_570"),
    @XmlEnumValue("E3_595")
    E_3_595("E3_595"),
    @XmlEnumValue("E3_596")
    E_3_596("E3_596"),
    @XmlEnumValue("E3_597")
    E_3_597("E3_597"),
    @XmlEnumValue("E3_880_001")
    E_3_880_001("E3_880_001"),
    @XmlEnumValue("E3_880_002")
    E_3_880_002("E3_880_002"),
    @XmlEnumValue("E3_880_003")
    E_3_880_003("E3_880_003"),
    @XmlEnumValue("E3_880_004")
    E_3_880_004("E3_880_004"),
    @XmlEnumValue("E3_881_001")
    E_3_881_001("E3_881_001"),
    @XmlEnumValue("E3_881_002")
    E_3_881_002("E3_881_002"),
    @XmlEnumValue("E3_881_003")
    E_3_881_003("E3_881_003"),
    @XmlEnumValue("E3_881_004")
    E_3_881_004("E3_881_004");
    private final String value;

    IncomeClassificationValueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IncomeClassificationValueType fromValue(String v) {
        for (IncomeClassificationValueType c: IncomeClassificationValueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
