//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.02 at 03:58:23 PM EEST 
//


package org.model.xjc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InvoiceExpensesClassificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceExpensesClassificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="invoiceMark" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="classificationMark" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="transactionMode">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                 &lt;minInclusive value="1"/>
 *                 &lt;maxInclusive value="1"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="invoicesExpensesClassificationDetails" type="{https://www.aade.gr/myDATA/expensesClassificaton/v1.0}InvoicesExpensesClassificationDetailType" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceExpensesClassificationType", namespace = "https://www.aade.gr/myDATA/expensesClassificaton/v1.0", propOrder = {
    "invoiceMark",
    "classificationMark",
    "transactionMode",
    "invoicesExpensesClassificationDetails"
})
public class InvoiceExpensesClassificationType {

    protected long invoiceMark;
    protected Long classificationMark;
    protected Integer transactionMode;
    protected List<InvoicesExpensesClassificationDetailType> invoicesExpensesClassificationDetails;

    /**
     * Gets the value of the invoiceMark property.
     * 
     */
    public long getInvoiceMark() {
        return invoiceMark;
    }

    /**
     * Sets the value of the invoiceMark property.
     * 
     */
    public void setInvoiceMark(long value) {
        this.invoiceMark = value;
    }

    /**
     * Gets the value of the classificationMark property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getClassificationMark() {
        return classificationMark;
    }

    /**
     * Sets the value of the classificationMark property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setClassificationMark(Long value) {
        this.classificationMark = value;
    }

    /**
     * Gets the value of the transactionMode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTransactionMode() {
        return transactionMode;
    }

    /**
     * Sets the value of the transactionMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTransactionMode(Integer value) {
        this.transactionMode = value;
    }

    /**
     * Gets the value of the invoicesExpensesClassificationDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoicesExpensesClassificationDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoicesExpensesClassificationDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvoicesExpensesClassificationDetailType }
     * 
     * 
     */
    public List<InvoicesExpensesClassificationDetailType> getInvoicesExpensesClassificationDetails() {
        if (invoicesExpensesClassificationDetails == null) {
            invoicesExpensesClassificationDetails = new ArrayList<InvoicesExpensesClassificationDetailType>();
        }
        return this.invoicesExpensesClassificationDetails;
    }

}
