//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.02 at 03:58:23 PM EEST 
//


package org.model.xjc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InvoiceSummaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceSummaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="totalNetValue" type="{http://www.aade.gr/myDATA/invoice/v1.0}AmountType"/>
 *         &lt;element name="totalVatAmount" type="{http://www.aade.gr/myDATA/invoice/v1.0}AmountType"/>
 *         &lt;element name="totalWithheldAmount" type="{http://www.aade.gr/myDATA/invoice/v1.0}AmountType"/>
 *         &lt;element name="totalFeesAmount" type="{http://www.aade.gr/myDATA/invoice/v1.0}AmountType"/>
 *         &lt;element name="totalStampDutyAmount" type="{http://www.aade.gr/myDATA/invoice/v1.0}AmountType"/>
 *         &lt;element name="totalOtherTaxesAmount" type="{http://www.aade.gr/myDATA/invoice/v1.0}AmountType"/>
 *         &lt;element name="totalDeductionsAmount" type="{http://www.aade.gr/myDATA/invoice/v1.0}AmountType"/>
 *         &lt;element name="totalGrossValue" type="{http://www.aade.gr/myDATA/invoice/v1.0}AmountType"/>
 *         &lt;element name="incomeClassification" type="{https://www.aade.gr/myDATA/incomeClassificaton/v1.0}IncomeClassificationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="expensesClassification" type="{https://www.aade.gr/myDATA/expensesClassificaton/v1.0}ExpensesClassificationType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceSummaryType", propOrder = {
    "totalNetValue",
    "totalVatAmount",
    "totalWithheldAmount",
    "totalFeesAmount",
    "totalStampDutyAmount",
    "totalOtherTaxesAmount",
    "totalDeductionsAmount",
    "totalGrossValue",
    "incomeClassification",
    "expensesClassification"
})
public class InvoiceSummaryType {

    @XmlElement(required = true)
    protected BigDecimal totalNetValue;
    @XmlElement(required = true)
    protected BigDecimal totalVatAmount;
    @XmlElement(required = true)
    protected BigDecimal totalWithheldAmount;
    @XmlElement(required = true)
    protected BigDecimal totalFeesAmount;
    @XmlElement(required = true)
    protected BigDecimal totalStampDutyAmount;
    @XmlElement(required = true)
    protected BigDecimal totalOtherTaxesAmount;
    @XmlElement(required = true)
    protected BigDecimal totalDeductionsAmount;
    @XmlElement(required = true)
    protected BigDecimal totalGrossValue;
    protected List<IncomeClassificationType> incomeClassification;
    protected List<ExpensesClassificationType> expensesClassification;

    /**
     * Gets the value of the totalNetValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalNetValue() {
        return totalNetValue;
    }

    /**
     * Sets the value of the totalNetValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalNetValue(BigDecimal value) {
        this.totalNetValue = value;
    }

    /**
     * Gets the value of the totalVatAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalVatAmount() {
        return totalVatAmount;
    }

    /**
     * Sets the value of the totalVatAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalVatAmount(BigDecimal value) {
        this.totalVatAmount = value;
    }

    /**
     * Gets the value of the totalWithheldAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalWithheldAmount() {
        return totalWithheldAmount;
    }

    /**
     * Sets the value of the totalWithheldAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalWithheldAmount(BigDecimal value) {
        this.totalWithheldAmount = value;
    }

    /**
     * Gets the value of the totalFeesAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalFeesAmount() {
        return totalFeesAmount;
    }

    /**
     * Sets the value of the totalFeesAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalFeesAmount(BigDecimal value) {
        this.totalFeesAmount = value;
    }

    /**
     * Gets the value of the totalStampDutyAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalStampDutyAmount() {
        return totalStampDutyAmount;
    }

    /**
     * Sets the value of the totalStampDutyAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalStampDutyAmount(BigDecimal value) {
        this.totalStampDutyAmount = value;
    }

    /**
     * Gets the value of the totalOtherTaxesAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalOtherTaxesAmount() {
        return totalOtherTaxesAmount;
    }

    /**
     * Sets the value of the totalOtherTaxesAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalOtherTaxesAmount(BigDecimal value) {
        this.totalOtherTaxesAmount = value;
    }

    /**
     * Gets the value of the totalDeductionsAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalDeductionsAmount() {
        return totalDeductionsAmount;
    }

    /**
     * Sets the value of the totalDeductionsAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalDeductionsAmount(BigDecimal value) {
        this.totalDeductionsAmount = value;
    }

    /**
     * Gets the value of the totalGrossValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalGrossValue() {
        return totalGrossValue;
    }

    /**
     * Sets the value of the totalGrossValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalGrossValue(BigDecimal value) {
        this.totalGrossValue = value;
    }

    /**
     * Gets the value of the incomeClassification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incomeClassification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncomeClassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncomeClassificationType }
     * 
     * 
     */
    public List<IncomeClassificationType> getIncomeClassification() {
        if (incomeClassification == null) {
            incomeClassification = new ArrayList<IncomeClassificationType>();
        }
        return this.incomeClassification;
    }

    /**
     * Gets the value of the expensesClassification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the expensesClassification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExpensesClassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExpensesClassificationType }
     * 
     * 
     */
    public List<ExpensesClassificationType> getExpensesClassification() {
        if (expensesClassification == null) {
            expensesClassification = new ArrayList<ExpensesClassificationType>();
        }
        return this.expensesClassification;
    }

}
