//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.02 at 03:58:23 PM EEST 
//


package org.model.xjc;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.model.xjc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.model.xjc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AadeBookInvoiceType }
     * 
     */
    public AadeBookInvoiceType createAadeBookInvoiceType() {
        return new AadeBookInvoiceType();
    }

    /**
     * Create an instance of {@link InvoicesDoc }
     * 
     */
    public InvoicesDoc createInvoicesDoc() {
        return new InvoicesDoc();
    }

    /**
     * Create an instance of {@link InvoiceRowType }
     * 
     */
    public InvoiceRowType createInvoiceRowType() {
        return new InvoiceRowType();
    }

    /**
     * Create an instance of {@link PaymentMethodDetailType }
     * 
     */
    public PaymentMethodDetailType createPaymentMethodDetailType() {
        return new PaymentMethodDetailType();
    }

    /**
     * Create an instance of {@link TaxTotalsType }
     * 
     */
    public TaxTotalsType createTaxTotalsType() {
        return new TaxTotalsType();
    }

    /**
     * Create an instance of {@link InvoiceSummaryType }
     * 
     */
    public InvoiceSummaryType createInvoiceSummaryType() {
        return new InvoiceSummaryType();
    }

    /**
     * Create an instance of {@link InvoiceHeaderType }
     * 
     */
    public InvoiceHeaderType createInvoiceHeaderType() {
        return new InvoiceHeaderType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link PartyType }
     * 
     */
    public PartyType createPartyType() {
        return new PartyType();
    }

    /**
     * Create an instance of {@link ShipType }
     * 
     */
    public ShipType createShipType() {
        return new ShipType();
    }

    /**
     * Create an instance of {@link IncomeClassificationsDoc }
     * 
     */
    public IncomeClassificationsDoc createIncomeClassificationsDoc() {
        return new IncomeClassificationsDoc();
    }

    /**
     * Create an instance of {@link InvoiceIncomeClassificationType }
     * 
     */
    public InvoiceIncomeClassificationType createInvoiceIncomeClassificationType() {
        return new InvoiceIncomeClassificationType();
    }

    /**
     * Create an instance of {@link IncomeClassificationType }
     * 
     */
    public IncomeClassificationType createIncomeClassificationType() {
        return new IncomeClassificationType();
    }

    /**
     * Create an instance of {@link InvoicesIncomeClassificationDetailType }
     * 
     */
    public InvoicesIncomeClassificationDetailType createInvoicesIncomeClassificationDetailType() {
        return new InvoicesIncomeClassificationDetailType();
    }

    /**
     * Create an instance of {@link ExpensesClassificationsDoc }
     * 
     */
    public ExpensesClassificationsDoc createExpensesClassificationsDoc() {
        return new ExpensesClassificationsDoc();
    }

    /**
     * Create an instance of {@link InvoiceExpensesClassificationType }
     * 
     */
    public InvoiceExpensesClassificationType createInvoiceExpensesClassificationType() {
        return new InvoiceExpensesClassificationType();
    }

    /**
     * Create an instance of {@link InvoicesExpensesClassificationDetailType }
     * 
     */
    public InvoicesExpensesClassificationDetailType createInvoicesExpensesClassificationDetailType() {
        return new InvoicesExpensesClassificationDetailType();
    }

    /**
     * Create an instance of {@link ExpensesClassificationType }
     * 
     */
    public ExpensesClassificationType createExpensesClassificationType() {
        return new ExpensesClassificationType();
    }

    /**
     * Create an instance of {@link AadeBookInvoiceType.PaymentMethods }
     * 
     */
    public AadeBookInvoiceType.PaymentMethods createAadeBookInvoiceTypePaymentMethods() {
        return new AadeBookInvoiceType.PaymentMethods();
    }

    /**
     * Create an instance of {@link AadeBookInvoiceType.TaxesTotals }
     * 
     */
    public AadeBookInvoiceType.TaxesTotals createAadeBookInvoiceTypeTaxesTotals() {
        return new AadeBookInvoiceType.TaxesTotals();
    }

}
